--- 
user: capuser
group: wwwadmin
docroot: /var/www/finance/current/public
cwd: /var/www/finance/current
log_file: log/mongrel.log
port: "8030"
environment: production
pid_file: tmp/pids/mongrel.pid
address: 127.0.0.1
servers: 1
